---
- name: Backing up Manjaro...
  hosts: localhost
  roles:
    #Configurations
    - roles/backup/configurations/kde-desktop
    - roles/backup/configurations/tmux
    - roles/backup/configurations/zsh
    - roles/backup/configurations/vim
    #Applications
    - roles/backup/applications/zed
    - roles/backup/applications/wireshark
    #Manjaro Build
    #- roles/backup/manjaro-build
