---
- name: Configuring timeshift...
  copy:
    src: "{{target_home_dir}}/manjaro-build/roles/setup/configurations/timeshift/files/timeshift.json"
    dest: /etc/timeshift/timeshift.json
  become: true
